services:
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9003:9003"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server --console-address ":9003" /data
    volumes:
      - gemtec-api-miniodata:/data
    networks:
      - gemtec-api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002"]
      interval: 30s
      timeout: 30s
      retries: 10

  postgres:
    container_name: gemtec-api-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gemtec
    networks:
      - gemtec-api-network
    volumes:
      - gemtec-api-postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "gemtec",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    container_name: gemtec-api-nestjs
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      - FIREBASE_SERVICE_ACCOUNT={"type":"service_account","project_id":"gemtec-e25e8"}
      - FIREBASE_PROJECT_ID=gemtec-e25e8
      - NESTJS_PORT=3001
      - NODE_ENV=development
    networks:
      - gemtec-api-network
    expose:
      - 3001
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma

  redis:
    container_name: gemtec-api-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - gemtec-api-network
    # Optional: for ephemeral dev usage, you might disable persistence:
    command: ["redis-server", "--appendonly", "no"]

volumes:
  gemtec-api-postgres-data:
  gemtec-api-miniodata:
networks:
  gemtec-api-network:
